InventorySystem/Models/ViewModels/HomeViewModel.cs
using InventorySystem.DataBase;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace InventorySystem.Models.ViewModels
{
    public class HomeViewModel
    {
        public HomeViewModel()
        {
            NewProducts = new List<Product_t>();
            ProductsFinishing = new List<Product_t>();
            LastSales = new List<Sell_t>();
        }
        public Decimal AbsoluteInventary { get; set; }

        public int TotalProducts { get; set; }

        public double SellsCash { get; set; }

        public int SellsTotal { get; set; }

        public double PurshaseCash { get; set; }

        public int PurchaseTotal { get; set; }

        public int Clients { get; set; }

        public int NewClients { get; set; }

        public List<Product_t> NewProducts { get; set; }

        public List<Product_t> ProductsFinishing { get; set; }

        public List<Sell_t> LastSales { get; set; }

        public Product_t Products { get; set; }

        public Sell_t Sell { get; set; }
    }
}

InventorySystem/Controllers/HomeController.cs
using InventorySystem.DataBase;
using InventorySystem.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace InventorySystem.Controllers
{
    public class HomeController : Controller
    {
        private InventorySystemEntities db = new InventorySystemEntities();
        HomeViewModel homeView = new HomeViewModel();
        // GET: Home
        public ActionResult Index(string SearchText)
        {
            LoadDashBoardData();

            if (!string.IsNullOrEmpty(SearchText))
            {
                //  var result = db.inventario_v.ToList().Where(s => s.Producto.Contains(SearchText));
                var result = db.Product_t.ToList().Where(s => s.name.ToLower().Contains(SearchText.ToLower()));

                return View(result.ToList());
            }
            return View(homeView);
        }

        private void LoadDashBoardData()
        {
            try
            {
                if (db.Product_t.Any())
                {
                    homeView.AbsoluteInventary = db.Product_t.Select(x => x.price).Sum();
                    homeView.TotalProducts = db.Product_t.Count();
                }

                if (db.Sell_t.Any(x => x.Operation_type_Id == 2))
                {
                    homeView.SellsCash = db.Sell_t.Where(x => x.Operation_type_Id == 2).Select(x => x.cash).Sum();

                    homeView.SellsTotal = db.Sell_t.Where(x => x.Operation_type_Id == 2).Count();
                }

                if (db.Sell_t.Any(x => x.Operation_type_Id == 1))
                {
                    homeView.PurshaseCash = db.Sell_t.Where(x => x.Operation_type_Id == 1).Select(x => x.cash).Sum();

                    homeView.PurchaseTotal = db.Sell_t.Where(x => x.Operation_type_Id == 1).Count();
                }

                if (db.Person_t.Any())
                {
                    homeView.Clients = db.Person_t.Where(x => x.person_type == 1).Count();

                    homeView.NewClients = db.Person_t.Where(x => x.person_type == 1).Count();
                }

                if (db.Product_t.Any())
                {
                    homeView.NewProducts = db.Product_t.OrderBy(x => x.creation_Date).Take(5).ToList();

                    homeView.ProductsFinishing = db.Product_t.Where(x => x.existence < 50).OrderBy(x => x.creation_Date).Take(5).ToList();
                }


                if (db.Sell_t.Any())
                {
                    homeView.LastSales = db.Sell_t.OrderBy(x => x.Id).Take(5).ToList();
                }
            }
            catch (Exception)
            {

            }
        }
    }
}

InventorySystem/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventorySystem.DataBase;

namespace InventorySystem.Controllers
{
    public class ProductController : Controller
    {
        private InventorySystemEntities db = new InventorySystemEntities();

        // GET: Product_t
        public ActionResult Index()
        {
            var product_t = db.Product_t.Include(p => p.Category_t).Include(p => p.Unit_t).Include(p => p.Warehouse_t);
            return View(product_t.ToList());
        }

        // GET: Product_t/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_t product_t = db.Product_t.Find(id);
            if (product_t == null)
            {
                return HttpNotFound();
            }
            return View(product_t);
        }

        // GET: Product_t/Create
        public ActionResult Create()
        {
            ViewBag.category_id = new SelectList(db.Category_t, "category_id", "name");
            ViewBag.unit_id = new SelectList(db.Unit_t, "unit_id", "description");
            ViewBag.warehouse_id = new SelectList(db.Warehouse_t, "warehouse_id", "name");
            return View();
        }

        // POST: Product_t/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "product_id,name,description,price,existence,unit_id,category_id,warehouse_id,last_update_date,creation_Date,last_user_update")] Product_t product_t)
        {
            if (ModelState.IsValid)
            {
                db.Product_t.Add(product_t);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.category_id = new SelectList(db.Category_t, "category_id", "name", product_t.category_id);
            ViewBag.unit_id = new SelectList(db.Unit_t, "unit_id", "description", product_t.unit_id);
            ViewBag.warehouse_id = new SelectList(db.Warehouse_t, "warehouse_id", "name", product_t.warehouse_id);
            return View(product_t);
        }

        // GET: Product_t/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_t product_t = db.Product_t.Find(id);
            if (product_t == null)
            {
                return HttpNotFound();
            }
            ViewBag.category_id = new SelectList(db.Category_t, "category_id", "name", product_t.category_id);
            ViewBag.unit_id = new SelectList(db.Unit_t, "unit_id", "description", product_t.unit_id);
            ViewBag.warehouse_id = new SelectList(db.Warehouse_t, "warehouse_id", "name", product_t.warehouse_id);
            return View(product_t);
        }

        // POST: Product_t/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "product_id,name,description,price,existence,unit_id,category_id,warehouse_id,last_update_date,creation_Date,last_user_update")] Product_t product_t)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product_t).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.category_id = new SelectList(db.Category_t, "category_id", "name", product_t.category_id);
            ViewBag.unit_id = new SelectList(db.Unit_t, "unit_id", "description", product_t.unit_id);
            ViewBag.warehouse_id = new SelectList(db.Warehouse_t, "warehouse_id", "name", product_t.warehouse_id);
            return View(product_t);
        }

        // GET: Product_t/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_t product_t = db.Product_t.Find(id);
            if (product_t == null)
            {
                return HttpNotFound();
            }
            return View(product_t);
        }

        // POST: Product_t/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product_t product_t = db.Product_t.Find(id);
            db.Product_t.Remove(product_t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InventorySystem/Controllers/SellController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventorySystem.DataBase;
using InventorySystem.Models.ViewModels;
using InventorySystemRepository;

namespace InventorySystem.Controllers
{
    public class SellController : Controller
    {
        private InventorySystemEntities db = new InventorySystemEntities();
        SellViewModel sellVm = new SellViewModel();
        UnitOfWork unit = new UnitOfWork();

        // GET: Sell
        public ActionResult Index()
        {
            SellViewModel sell = new SellViewModel()
            {
                
                Sells = db.Sell_t.Include(s => s.Person_t).Include(s => s.Operation_type_t).Include(s => s.Operation_t).ToList()
            };
            if (sell.Sells.Any(x=>x.Operation_type_Id == 2))
            {
                sell.Sells = sell.Sells.Where(x => x.Operation_type_Id == 2).ToList();
            }
            return View(sell);
        }

        // GET: Sell/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sell_t sell_t = db.Sell_t.Find(id);
            if (sell_t == null)
            {
                return HttpNotFound();
            }
            return View(sell_t);
        }

        // GET: Sell/Create
        public ActionResult Create()
        {
            SellViewModel sell = new SellViewModel()
            {

                Sells = db.Sell_t.Include(s => s.Person_t).Include(s => s.Operation_type_t).Include(s => s.Operation_t).Where(x => x.Operation_type_Id == 2).ToList()
            };

            ViewBag.Person_Id = new SelectList(db.Person_t.Where(x=>x.person_type ==1), "Id", "name");
            ViewBag.Operation_type_Id = new SelectList(db.Operation_type_t, "Id", "Description");
            ViewBag.user_id = new SelectList(db.User_t, "user_id", "email");
            ViewBag.product_id = new SelectList(db.Product_t, "product_id", "name");
            return View();
        }

        // POST: Sell/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,total,cash,discount,Person_Id,Operation_type_Id,product_id")] SellViewModel sellVm)
        {
           sellVm.user_id = Convert.ToInt32(User.Identity.Name);

           Sell_t sell = new Sell_t()
            {
                User_t = sellVm.User_t,
                Person_t = sellVm.Person_t,
                total = sellVm.total,
                cash = sellVm.cash,
                discount = sellVm.discount,
                Person_Id = sellVm.Person_Id,
                Operation_type_Id = 2,
                user_id = sellVm.user_id
            };

            Operation_t op = new Operation_t();
            op.product_id = sellVm.product_id;
            op.Sell_Id = sell.Id;
            op.Operation_type_Id = 2;
            string result = string.Empty;
            if (ModelState.IsValid)
            {
                result = unit.SellRepository.CreateOperation(sell, op);
                if (result == "OK")
                {
                    unit.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ModelState.AddModelError("", "Error: " + result);
            ViewBag.Person_Id = new SelectList(db.Person_t.Where(x => x.person_type == 1), "Id", "name", sellVm.Person_Id);
            ViewBag.Operation_type_Id = new SelectList(db.Operation_type_t, "Id", "Description", sellVm.Operation_type_Id);
            ViewBag.user_id = new SelectList(db.User_t, "user_id", "email", sellVm.user_id);
            ViewBag.product_id = new SelectList(db.Product_t, "product_id", "name", sellVm.product_id);

            return View(sellVm);
        }

        // GET: Sell/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sell_t sell_t = db.Sell_t.Find(id);
            if (sell_t == null)
            {
                return HttpNotFound();
            }
            ViewBag.Person_Id = new SelectList(db.Person_t.Where(x => x.person_type == 1), "Id", "name", sell_t.Person_Id);
            ViewBag.Operation_type_Id = new SelectList(db.Operation_type_t, "Id", "Description", sell_t.Operation_type_Id);
            ViewBag.user_id = new SelectList(db.User_t, "user_id", "email", sell_t.user_id);
            ViewBag.product_id = new SelectList(db.Product_t, "product_id", "name", sellVm.product_id);

            return View(sell_t);
        }

        // POST: Sell/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,total,cash,discount,Person_Id,user_id")] Sell_t sell_t)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sell_t).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Person_Id = new SelectList(db.Person_t.Where(x => x.person_type == 1), "Id", "name", sell_t.Person_Id);
            ViewBag.Operation_type_Id = new SelectList(db.Operation_type_t, "Id", "Description", sell_t.Operation_type_Id);
            ViewBag.user_id = new SelectList(db.User_t, "user_id", "email", sell_t.user_id);
            ViewBag.product_id = new SelectList(db.Product_t, "product_id", "name", sellVm.product_id);

            return View(sell_t);
        }

        // GET: Sell/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sell_t sell_t = db.Sell_t.Find(id);
            if (sell_t == null)
            {
                return HttpNotFound();
            }
            return View(sell_t);
        }

        // POST: Sell/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Sell_t sell_t = db.Sell_t.Find(id);
            db.Sell_t.Remove(sell_t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

InventorySystem/Views/Home/Index.cshtml
@model InventorySystem.Models.ViewModels.HomeViewModel

@{
    ViewBag.Title = "Panel";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-purple">
            <span class="info-box-icon"><i class="fa fa-tags"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Inventario Absoluto</span>
                <span class="info-box-number">@Model.AbsoluteInventary</span>
                <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                </div>
                <span class="progress-description">
                    Productos en stock: @Model.TotalProducts
                </span>
            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-green">
            <span class="info-box-icon"><i class="fa fa-money"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Ventas 2018</span>
                <span class="info-box-number">@Model.SellsCash</span>
                <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                </div>
                <span class="progress-description">
                    Ventas emitidas: @Model.SellsTotal
                </span>
            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->
    </div>
    <!-- /.col -->
    <!-- fix for small devices only -->
    <div class="clearfix visible-sm-block"></div>
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-yellow">
            <span class="info-box-icon"><i class="fa fa-shopping-cart"></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Compras 2018</span>
                <span class="info-box-number">@Model.PurshaseCash</span>
                <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                </div>
                <span class="progress-description">
                    Compras realizadas: @Model.PurchaseTotal
                </span>
            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="info-box bg-aqua">
            <span class="info-box-icon"><i class="fa fa-users "></i></span>
            <div class="info-box-content">
                <span class="info-box-text">Clientes</span>
                <span class="info-box-number">@Model.Clients </span>
                <div class="progress">
                    <div class="progress-bar" style="width: 100%"></div>
                </div>
                <span class="progress-description">
                    Clientes nuevos: @Model.NewClients
                </span>
            </div><!-- /.info-box-content -->
        </div><!-- /.info-box -->
    </div>
    <!-- /.col -->
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Reporte de ventas 2018</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="row">
                    <div class="col-md-8">
                        <p class="text-center">
                            <strong>Compras &amp; Ventas 2018</strong>
                        </p>
                        <div class="chart">
                            <canvas id="barChart" style="height: 380px; width: 816px;" width="1020" height="475"></canvas>
                        </div>
                    </div><!-- /.col -->
                    <div class="col-md-4">
                        <!-- Info Boxes Style 2 -->
                        <!--ENDING PRODUCT LIST -->
                        <div class="box box-primary">
                            <div class="box-header ">
                                <h3 class="box-title color">Productos acabándose</h3>
                            </div><!-- /.box-header -->
                            <div class="box-body">
                                <ul class="products-list product-list-in-box">
                                    @foreach (var item in Model.ProductsFinishing)
                                    {
                                        <li class="item">
                                            @*<div class="product-img">
                                                <img src="img/productos/product.png" alt="Product Image">
                                            </div>*@
                                            <div class="product-info">
                                                <a href="@Url.Action("Edit", "Product",new { id= item.product_id })" class="product-title"> @Html.DisplayFor(modelItem => item.name)<span class="label label-danger pull-right">Restantes: @Html.DisplayFor(modelItem => item.existence) </span></a>
                                                <span class="product-description">
                                                    @Html.DisplayFor(modelItem => item.description)
                                                </span>
                                            </div>
                                        </li><!-- /.item -->
                                    }
                                </ul>
                            </div><!-- /.box-body -->
                            <div class="box-footer text-center">
                                <a href="@Url.Action("Index", "Product")" class="uppercase">Ver todos los productos</a>
                            </div><!-- /.box-footer -->
                        </div><!-- /.box -->
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- ./box-body -->
            <div class="box-footer">
            </div><!-- /.box-footer -->
        </div><!-- /.box -->
    </div><!-- /.col -->


</div><!-- /.col -->

<div class="row">
    <!-- Left col -->
    <div class="col-md-8">
        <!-- TABLE: LATEST ORDERS -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Últimas ventas</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">
                <div class="table-responsive">
                    <table class="table no-margin">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Sell.Id)
                            </th>
                            <th>
                                Cliente
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Sell.creation_Date)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Sell.total)
                            </th>
                        </tr>
                        @foreach (var item in Model.LastSales)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Person_t.name)
                            </td>
                            <td>
                                @DateTime.Now
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.total)
                            </td>
                        </tr>
                        }
                    </table>
                </div><!-- /.table-responsive -->
            </div><!-- /.box-body -->
            <div class="box-footer clearfix">
                <a href="@Url.Action("Create", "Sell")" class="btn btn-sm btn-default btn-flat pull-left">Nueva venta</a>
                @*<a href="manage_invoice.php" class="btn btn-sm btn-default btn-flat pull-right">Ver todas las facturas</a>*@
            </div><!-- /.box-footer -->
        </div><!-- /.box -->
    </div><!-- /.col -->
    <div class="col-md-4">

        <!-- PRODUCT LIST -->
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Nuevos productos</h3>
                <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                </div>
            </div><!-- /.box-header -->
            <div class="box-body">
                <ul class="products-list product-list-in-box">
                    @foreach (var item in Model.NewProducts)
                    {
                        <li class="item">
                            @*<div class="product-img">
                    <img src="img/productos/product.png" alt="Product Image">
                </div>*@
                            <div class="product-info">
                                <a href="@Url.Action("Edit", "Product",new { id= item.product_id })" class="product-title"> @Html.DisplayFor(modelItem => item.name)<span class="label label-info pull-right">Precio: @Html.DisplayFor(modelItem => item.price)</span></a>
                                <span class="product-description">
                                    @Html.DisplayFor(modelItem => item.description)
                                </span>
                            </div>
                        </li><!-- /.item -->
                    }
                </ul>
            </div><!-- /.box-body -->
            <div class="box-footer text-center">
                <a href="@Url.Action("Index", "Product")" class="uppercase">Ver todos los productos</a>
            </div><!-- /.box-footer -->
        </div><!-- /.box -->
    </div><!-- /.col -->
</div>